version: '3.9'

services:
  postgres:
    image: citusdata/citus
    container_name: postgres_perpus
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: perpus_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    container_name: mongo_perpus
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - perpus_net
    volumes:
      - mongodata:/data/db
  mongo_perpus_secondary:
    image: mongo:6
    container_name: mongo_perpus_secondary
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27020:27017"
    networks:
      - perpus_net
    volumes:
      - mongo_secondary_data:/data/db

  mongo_init:
    image: mongo:6
    container_name: mongo_rs_initiate
    depends_on:
      - mongodb
      - mongo_perpus_secondary
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - perpus_net
    entrypoint: ["bash", "-c", "sleep 10 && mongosh --host mongo_perpus --eval 'load(\"/docker-entrypoint-initdb.d/init-mongo.js\")'"]

  redis:
    image: redis:7.0
    container_name: redis_perpus
    ports:
      - "6379:6379"
    networks:
      - perpus_net
  python_app:
    build: .
    container_name: python_app
    depends_on:
      - postgres
      - mongodb
      - mongo_perpus_secondary
      - redis
      - mongo_init
    volumes:
      - .:/app
    networks:
      - perpus_net   
    command: ["sh", "-c", "python library_app_integration.py; tail -f /dev/null"]
    
volumes:
  pgdata:
  mongodata:
  redisdata:
  mongo_secondary_data:
networks:
  perpus_net: